Rich traceback (most recent call last):
  File "./tests/test_all.py", line 30, in test_max_value_str_len
    f(10000)
      out = <_io.Strin...
  File "./tests/test_all.py", line 68, in f
    return 1 // (n * 0)
      n = 10000
      s1 = 'short str...
      l1 = 'long stri...
      us = <exception while printing> Traceback (most recent call last):
          File "./rich_traceback/__init__.py", line 60, in _to_cropped_str
            return _crop(repr(obj), max_value_str_len, ellipsis)
          File "./tests/test_all.py", line 82, in __repr__
            raise ValueError("please don't print me")
        ValueError: please don't print me
        
builtins.ZeroDivisionError: integer division or modulo by zero
