ERROR    test-logger:print.py:20 Traceback with variables (most recent call last):
ERROR    test-logger:print.py:20   File ".../tests/test_print.py", line 44, in test_logger_as_file
ERROR    test-logger:print.py:20     f(10)
ERROR    test-logger:print.py:20       caplog = <_pytest.logging.LogCaptureFixture object at 0x...>
ERROR    test-logger:print.py:20   File ".../tests/test_print.py", line 50, in f
ERROR    test-logger:print.py:20     return n / 0
ERROR    test-logger:print.py:20       n = 10
ERROR    test-logger:print.py:20 builtins.ZeroDivisionError: division by zero
