ERROR    test-logger:print.py:19 Traceback with variables (most recent call last):
ERROR    test-logger:print.py:19   File "...omitted for tests only.../tests/test_print.py", line 74, in test_logger_as_file
ERROR    test-logger:print.py:19     f(10)
ERROR    test-logger:print.py:19       caplog = <_pytest.logging.LogCaptureFixture object at 0x...omitted for tests only...>
ERROR    test-logger:print.py:19   File "...omitted for tests only.../tests/test_print.py", line 80, in f
ERROR    test-logger:print.py:19     return n / 0
ERROR    test-logger:print.py:19       n = 10
ERROR    test-logger:print.py:19 builtins.ZeroDivisionError: division by zero
