Traceback with variables (most recent call last):
  File ".../tests/test_print.py", line 50, in f
    return n / 0
      n = 10
builtins.ZeroDivisionError: division by zero
